# Databricks notebook source
# MAGIC %md
# MAGIC ## File Arrival
# MAGIC #### When a file arrives in ADLS, trigger this workflow to register the file into the fits_files_raw table

# COMMAND ----------


cat = dbutils.widgets.get('cat')
db = dbutils.widgets.get('db')
adls = dbutils.widgets.get('adls')

# COMMAND ----------

# MAGIC %sql create table if not exists ${cat}.${db}.fits_files_raw (imageid bigint generated by default as identity, path string, modificationTime timestamp, length bigint, content binary)

# COMMAND ----------

adls_url = f'{adls}.dfs.core.windows.net'
images_folder = f'abfss://{cat}@{adls_url}/images/light/'
checkpoint_folder = f'abfss://{cat}@{adls_url}/checkpoints/{cat}/images/light/fits_auto_loader'

(spark.readStream
  .format('cloudFiles')
  .option('cloudFiles.format', 'binaryfile')
  .option('cloudFiles.schemaLocation', checkpoint_folder)
  .load(images_folder)
  .select('path', 'modificationTime', 'length', 'content')
  .writeStream
  .option('checkpointLocation', checkpoint_folder)
  .trigger(availableNow=True)
  .toTable(f'{cat}.{db}.fits_files_raw'))